# Desafio Code:Nation - enem-1

### Importando o CSV

In [1]:
import csv

In [2]:
import pandas as pd
data = "train.csv"
df = pd.read_csv(data)

In [4]:
df

,Unnamed: 0,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,...,Q041,Q042,Q043,Q044,Q045,Q046,Q047,Q048,Q049,Q050
0,1,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,2016,4314902,Porto Alegre,43,RS,24,M,0.0,...,5.0,A,A,A,A,A,A,A,B,D
1,2,2c3acac4b33ec2b195d77e7c04a2d75727fad723,2016,2304707,Granja,23,CE,17,F,0.0,...,NaN,A,A,C,A,B,A,A,C,A
2,3,f4545f8ccb9ff5c8aad7d32951b3f251a26e6568,2016,2304400,Fortaleza,23,CE,21,F,0.0,...,NaN,A,A,A,A,C,A,A,B,A
3,4,3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe,2016,3304557,Rio de Janeiro,33,RJ,25,F,0.0,...,5.0,C,A,A,A,A,D,A,A,A
4,5,bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268,2016,1302603,Manaus,13,AM,28,M,0.0,...,NaN,A,A,A,A,A,A,A,A,A
5,6,a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1,2016,2902005,Aracatu,29,BA,18,F,0.0,...,NaN,A,A,A,A,A,A,A,A,A
6,7,63b4e128e9ffe8ab27f5d093db1976ef4f353e0a,2016,5102637,Campo Novo do Parecis,51,MT,18,F,0.0,...,0.0,A,A,A,B,B,A,A,A,A
7,8,2eb189d4912f64b19d1967e8e84b6141aba18770,2016,4301602,Bagé,43,RS,18,F,0.0,...,NaN,C,A,A,A,A,D,A,A,A
8,9,5822cb43e0800429be2084b3f86a63aaa73fa66c,2016,2601904,Bezerros,26,PE,16,F,0.0,...,NaN,D,A,A,A,B,A,D,B,A
9,10,94f7e277f87cd58e10a45da4ad5dd168651cf3ef,2016,3152501,Pouso Alegre,31,MG,24,M,0.0,...,NaN,A,A,A,B,D,A,B,B,C
10,11,3c44449ad09dc6a72c77c3bd3b5fd06a6d3f66e8,2016,2603207,Caetés,26,PE,29,F,0.0,...,5.0,A,A,A,A,A,A,A,B,C
11,12,6f721ecb245bd74eaeda78b8d8135e8adeba6dc0,2016,2111300,São Luís,21,MA,17,F,0.0,...,NaN,A,A,A,A,B,A,A,A,A
12,13,70b1dacb515d1aecead8a53cb465a70fda4b62b6,2016,4314902,Porto Alegre,43,RS,27,M,NaN,...,NaN,A,A,A,B,A,A,D,A,B
13,14,8570b9be0b2b629d00743d0de77cd95a84a46fbc,2016,2304400,Fortaleza,23,CE,19,F,0.0,...,5.0,A,A,A,A,A,A,A,A,A
14,15,67a173ad63a2a3f77c8905b49e83084b7c1cd6b0,2016,2401859,Caiçara do Norte,24,RN,18,M,0.0,...,NaN,A,A,A,A,A,A,A,A,A
15,16,4e17008781ab3d721804ffe992884f86c37dcb4c,2016,5002704,Campo Grande,50,MS,18,F,0.0,...,5.0,A,A,A,A,A,A,A,A,A
16,17,6118b53a6c928609d5ec78f7b6ae463ee3f766e3,2016,4108403,Francisco Beltrão,41,PR,16,M,0.0,...,5.0,C,A,A,A,C,D,A,A,A
17,18,036bce628d802e0da1fc727057dd40e979a03ac3,2016,2101202,Bacabal,21,MA,24,F,0.0,...,5.0,A,A,A,B,B,A,A,B,A
18,19,e2550a9dbfe4dfa31af61ab8cbdd08de283fd7ba,2016,1501709,Bragança,15,PA,20,M,0.0,...,NaN,A,A,A,A,A,A,A,B,A
19,20,fa8d39d295f07f351cbff175dcfe01a4cbb49ca3,2016,3131307,Ipatinga,31,MG,21,F,1.0,...,NaN,A,A,A,A,D,A,A,B,D
20,21,bedf9d4bf2c29669d24ef9ed9fa4bb6b8a2b574b,2016,3162005,São Gonçalo do Sapucaí,31,MG,18,F,0.0,...,NaN,A,A,A,A,B,A,A,A,A
21,22,5458db66588b99384d711f24a5e77d2befb2bec9,2016,5300108,Brasília,53,DF,24,M,0.0,...,3.0,A,A,A,B,A,A,B,B,B
22,23,f2dda998a10d8f259dec0018a0a0aefafb66dcf7,2016,4317103,Sant'Ana do Livramento,43,RS,24,M,0.0,...,NaN,A,B,B,B,A,A,B,B,B
23,24,fe981a60436f1d9e533a28c67dd66c72290ce7c7,2016,4101705,Araruna,41,PR,17,F,0.0,...,NaN,A,A,A,B,C,A,A,C,A
24,25,f08085c95978cded4e8009e734772d2889c6ab1d,2016,3101607,Alfenas,31,MG,30,F,1.0,...,NaN,A,A,A,A,A,A,A,A,A
25,26,2600ee9cbb63e8dc65423f18d2f33c8ad198edfe,2016,3143302,Montes Claros,31,MG,18,F,0.0,...,NaN,A,A,A,A,A,A,A,A,A
26,27,75182e8460c3cae7808fbe4c3475c15e232327dd,2016,5210562,Itaguari,52,GO,22,M,0.0,...,1.0,A,A,A,A,A,A,A,B,A
27,28,9f1f0f639f56faed5cdb4db727692f9a49f7818b,2016,3205002,Serra,32,ES,19,M,0.0,...,NaN,A,A,A,B,B,A,B,B,B
28,29,45837167deb9a4e1969d5d9bdb31e8bfe7c94017,2016,3550308,São Paulo,35,SP,19,F,0.0,...,NaN,A,A,A,B,B,A,A,B,B
29,30,e1268d2857278d8ec8055524bc29cc16b5c4174f,2016,4109401,Guarapuava,41,PR,21,M,1.0,...,4.0,A,A,A,A,A,A,A,B,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13700,4557,37a01085b6a3345478b71e1ed93b8b4dd833650e,2016,2306504,Itapiúna,23,CE,17,F,NaN,...,NaN,A,A,A,A,B,A,A,A,A
13701,4558,ef533af96c6dd2604fc87fb30c2ff73893e726a7,2016,2307304,Juazeiro do Norte,23,CE,17,M,0.0,...,NaN,A,A,A,A,B,A,A,A,A
13702,4559,1e516d1c481add66acd28607e6d6c0119942bd8e,2016,5006606,Ponta Porã,50,MS,21,F,0.0,...,NaN,A,A,A,A,A,A,A,A,A
13703,4560,dc89e10a9546eb603496a8c3ad46f2ab3accb11c,2016,2304236,Croatá,23,CE,18,F,0.0,...,NaN,A,A,A,A,C,A,A,A,A
13704,4561,f8fd234e2b5b90db7f37b31acda5be3654e3da13,2016,1506906,Santarém Novo,15,PA,18,M,0.0,...,NaN,A,A,A,A,A,A,A,A,A
13705,4562,522bee7065c46c474a3a0c60186832e0a2410901,2016,4314902,Porto Alegre,43,RS,43,F,1.0,...,NaN,A,A,A,B,A,A,A,A,B
13706,4563,8e5ae93f4732c79d2bbcb139ee75a89ff0de281d,2016,3550308,São Paulo,35,SP,18,M,0.0,...,2.0,A,A,A,A,B,A,A,A,A
13707,4564,80323267166e6abc30d96cb470a6edfd768898f0,2016,3303203,Nilópolis,33,RJ,17,F,0.0,...,NaN,C,A,A,A,B,D,A,A,A
13708,4565,1ba84897d0d10c9dbe186252e23b3933f7d6d1c6,2016,2308401,Missão Velha,23,CE,18,M,0.0,...,NaN,A,A,A,A,C,A,A,A,A
13709,4566,f59008734018aa5d15229f071225919ae4f69360,2016,3304557,Rio de Janeiro,33,RJ,19,F,0.0,...,NaN,A,A,A,A,A,A,A,A,A
13710,4567,f9a93119ecb292ade75006f36a9b3bc015fe5bab,2016,2910800,Feira de Santana,29,BA,17,F,0.0,...,NaN,C,A,A,A,C,D,A,A,B
13711,4568,bc6ea97fcc031786198e58ca5485d2648a2145fb,2016,2703007,Ibateguara,27,AL,17,F,0.0,...,NaN,A,A,A,A,C,A,A,A,D
13712,4569,4af33e274971853b07ecb5e0b74bad5416712067,2016,3205200,Vila Velha,32,ES,19,F,0.0,...,NaN,D,A,A,A,A,D,A,A,A
13713,4570,e60cbd0026dae31e4f0580a909465c83355ea282,2016,1100205,Porto Velho,11,RO,25,M,NaN,...,NaN,A,A,A,A,A,A,A,A,A
13714,4571,716beeb2bc3a13541defc5cedc3b95d816e5733b,2016,3304557,Rio de Janeiro,33,RJ,18,M,0.0,...,NaN,C,A,A,A,B,D,A,A,C
13715,4572,99cfec493fefde4fcec60fd8c1e3eb1fe891fb31,2016,4108403,Francisco Beltrão,41,PR,24,F,0.0,...,5.0,A,A,A,A,A,A,A,C,A
13716,4573,00bb288d1b225bf07136b1d6e5a20a0fa7f7e2a9,2016,4209003,Joaçaba,42,SC,18,M,NaN,...,NaN,A,A,A,A,A,A,A,A,A
13717,4574,334d908475f66eceb76ddf22709c94247f0649b9,2016,2313302,Tauá,23,CE,17,F,NaN,...,NaN,A,A,A,A,B,A,A,A,A
13718,4575,6df66a7695e5cf77c2dcb805d31a0ee40fbac91b,2016,2307254,Jijoca de Jericoacoara,23,CE,16,M,0.0,...,NaN,A,A,A,A,C,A,A,A,A
13719,4576,5d8e3b11e9987d9da2239e151fd470a23d236ff7,2016,2614303,Moreilândia,26,PE,19,F,0.0,...,NaN,A,A,A,B,A,A,A,A,A
13720,4577,1e515548a3502e1c1828dc3066e6f290964b4f52,2016,4305108,Caxias do Sul,43,RS,18,F,0.0,...,3.0,A,A,A,A,B,A,A,A,A
13721,4578,60b5439a4c016b9659f45755609e9172e00d5d1c,2016,3301702,Duque de Caxias,33,RJ,16,F,0.0,...,NaN,A,A,A,A,B,A,A,A,A
13722,4579,a78cd7c85a7ed2a29190ed3e40a8cf8dad2d7335,2016,3201209,Cachoeiro de Itapemirim,32,ES,25,M,0.0,...,NaN,A,A,A,A,A,A,A,A,A
13723,4580,33852615a84f6d2ac089f7fe9697ac513b21c1ed,2016,3306107,Valença,33,RJ,16,F,0.0,...,NaN,A,A,A,A,C,A,A,A,A
13724,4581,305161d5bd5ba3ab0059debf906e875a3184996c,2016,3300100,Angra dos Reis,33,RJ,23,M,2.0,...,5.0,B,A,A,A,D,A,A,A,D
13725,4582,aadf671ef8c1c6efa42e69432093ab83c17a52ac,2016,3502903,Araçoiaba da Serra,35,SP,20,M,0.0,...,NaN,A,A,A,A,A,A,A,A,A
13726,4583,461f7ef2753d9d5fa0b054930d6b0e0eec318e81,2016,2613800,São Vicente Ferrer,26,PE,33,F,0.0,...,NaN,A,A,B,B,A,A,A,A,A
13727,4584,5354503700ecf2388f68990435390b6e1ad454ee,2016,4322186,Tupanci do Sul,43,RS,15,F,0.0,...,NaN,A,A,A,A,C,A,A,A,A
13728,4585,c7a9e94a42bd76b7978f13c013a61702e36cc42c,2016,3303203,Nilópolis,33,RJ,36,M,1.0,...,5.0,A,A,A,A,D,A,A,A,D
13729,4586,0af8939c470a600b30bdaa80375ee0db848b0e35,2016,4100400,Almirante Tamandaré,41,PR,17,M,0.0,...,NaN,A,A,A,A,B,A,A,A,A

### Separando apenas as colunas necessárias

In [97]:
enem = pd.DataFrame(df, columns=['NU_INSCRICAO', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO'])

In [98]:
enem.head(10)

,NU_INSCRICAO,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,436.3,495.4,581.2,399.4,520.0
1,2c3acac4b33ec2b195d77e7c04a2d75727fad723,474.5,544.1,599.0,459.8,580.0
2,f4545f8ccb9ff5c8aad7d32951b3f251a26e6568,NaN,NaN,NaN,NaN,NaN
3,3d6ec248fef899c414e77f82d5c6d2bffbeaf7fe,NaN,NaN,NaN,NaN,NaN
4,bf896ac8d3ecadd6dba1dfbf50110afcbf5d3268,NaN,NaN,NaN,NaN,NaN
5,a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1,439.7,583.2,410.9,364.5,620.0
6,63b4e128e9ffe8ab27f5d093db1976ef4f353e0a,420.1,604.2,484.5,529.2,560.0
7,2eb189d4912f64b19d1967e8e84b6141aba18770,619.6,625.8,611.2,566.7,620.0
8,5822cb43e0800429be2084b3f86a63aaa73fa66c,500.5,555.2,521.8,372.4,680.0
9,94f7e277f87cd58e10a45da4ad5dd168651cf3ef,NaN,NaN,NaN,NaN,NaN

### Eliminando os valores Nulos

In [99]:
enem = enem.dropna(axis=0, how='any')

In [100]:
enem.head(10)

,NU_INSCRICAO,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,436.3,495.4,581.2,399.4,520.0
1,2c3acac4b33ec2b195d77e7c04a2d75727fad723,474.5,544.1,599.0,459.8,580.0
5,a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1,439.7,583.2,410.9,364.5,620.0
6,63b4e128e9ffe8ab27f5d093db1976ef4f353e0a,420.1,604.2,484.5,529.2,560.0
7,2eb189d4912f64b19d1967e8e84b6141aba18770,619.6,625.8,611.2,566.7,620.0
8,5822cb43e0800429be2084b3f86a63aaa73fa66c,500.5,555.2,521.8,372.4,680.0
10,3c44449ad09dc6a72c77c3bd3b5fd06a6d3f66e8,413.4,407.9,533.9,419.6,520.0
11,6f721ecb245bd74eaeda78b8d8135e8adeba6dc0,503.4,509.6,490.1,369.9,580.0
12,70b1dacb515d1aecead8a53cb465a70fda4b62b6,402.6,556.9,599.0,464.2,360.0
14,67a173ad63a2a3f77c8905b49e83084b7c1cd6b0,477.8,462.9,511.9,453.4,360.0

### Calculando as médias

In [109]:
enem['MEDIA']= ((enem['NU_NOTA_MT'] * 3) + (enem['NU_NOTA_CN'] * 2) + (enem['NU_NOTA_LC'] * 1.5) + (enem['NU_NOTA_CH'] * 1) + (enem['NU_NOTA_REDACAO'] * 3))/5

In [110]:
enem.head(10)

,NU_INSCRICAO,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,MEDIA
0,ed50e8aaa58e7a806c337585efee9ca41f1eb1ad,436.3,495.4,581.2,399.4,520.0,999.60
1,2c3acac4b33ec2b195d77e7c04a2d75727fad723,474.5,544.1,599.0,459.8,580.0,1102.20
5,a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1,439.7,583.2,410.9,364.5,620.0,1006.49
6,63b4e128e9ffe8ab27f5d093db1976ef4f353e0a,420.1,604.2,484.5,529.2,560.0,1087.75
7,2eb189d4912f64b19d1967e8e84b6141aba18770,619.6,625.8,611.2,566.7,620.0,1268.38
8,5822cb43e0800429be2084b3f86a63aaa73fa66c,500.5,555.2,521.8,372.4,680.0,1099.22
10,3c44449ad09dc6a72c77c3bd3b5fd06a6d3f66e8,413.4,407.9,533.9,419.6,520.0,970.87
11,6f721ecb245bd74eaeda78b8d8135e8adeba6dc0,503.4,509.6,490.1,369.9,580.0,1020.25
12,70b1dacb515d1aecead8a53cb465a70fda4b62b6,402.6,556.9,599.0,464.2,360.0,946.64
14,67a173ad63a2a3f77c8905b49e83084b7c1cd6b0,477.8,462.9,511.9,453.4,360.0,925.31

### Criando um dataframe com o resultado

In [111]:
resultado = pd.DataFrame(enem, columns=['NU_INSCRICAO', 'MEDIA'])

In [112]:
resultado.head()

                               NU_INSCRICAO    MEDIA
0  ed50e8aaa58e7a806c337585efee9ca41f1eb1ad   999.60
1  2c3acac4b33ec2b195d77e7c04a2d75727fad723  1102.20
5  a37c99ec251d4f6e8ddbeabadf1c87fdbfddc4d1  1006.49
6  63b4e128e9ffe8ab27f5d093db1976ef4f353e0a  1087.75
7  2eb189d4912f64b19d1967e8e84b6141aba18770  1268.38

In [113]:
resultado = resultado.sort_values(['MEDIA'], ascending=False)

In [120]:
resultado = resultado.head(20)

In [121]:
resultado

                                   NU_INSCRICAO    MEDIA
10801  848daf808904864c1ee5d51545a2539e2dcbe901  1751.71
3226   97166da67df0908861a868cf318b277c4bdbb0da  1739.25
3682   b733ccac4e5b7c1da0448f1dad7990ec0793b1d2  1720.98
9011   78ca18b6fea7ccd3e067b3945cf200f8686209a7  1716.40
4755   8588b01c2ff81ad3c9ff31cd89fc094896c4aa69  1708.71
12707  19982f867b8f23a829a2f738374770708ec7f263  1700.87
6039   17ae668ce9041105883e9db101d614f58d526f66  1698.58
10219  3326c76719930f9838bc9ef803fe1b73a1668723  1689.04
1509   41489fd85a5d0cb6e397fb5ebcd19d32e9265cb7  1685.95
3535   32767c1a152919a1f72fa91afe19bb7c559f2824  1681.58
11334  ac5057ba1f029c2c37bc55c82f3ea3e4b8bcb0ce  1678.61
10951  7c7c16a3ebd04e3b4a42e086a447a64fc6fa0996  1669.45
9602   e9a67323f3cce292a7fd1528311470edb38f82d9  1665.71
4564   9eaa35afce755aeef24faee5ec0e78612f52b56c  1659.42
5913   c0bb9d9a29e686a5ef35f2443738d4bd8544a290  1655.89
3792   c771c44232f6ae553494cf7085f2b3e515841133  1654.41
499    4c29d5913f759e503efae77c531a713d48dfb512  1653.37
13191  61f38d59bbcfa4897a2e14740bec95e087e2e06f  1651.34
3080   b8912a162392742129d79ff0c625cfc02a425811  1645.12
10387  05a0ee9c17758662d1e5a985cac6d7e0938d3a58  1642.04

### Exportando a Resposta em arquivo .CSV

In [122]:
resultado.to_csv('answer.csv', index=False)